### PR TITLE
Implicit waiting has been set up when creating a browser instance #17

### PR DESCRIPTION
**Pull request by GoshkaEgoshka**
In modified files has been deleted implicity_wait
In browser.py was added implicity_wait

### CODE REVIEW

**Comment by GoshkaEgoshka** [comment]
> In oct/pages/registration.py, you also need to remove implicitly_wait on 8, 34 and 50 lines.

Thanks! I fixed it

**Comment by mistergreen22** [comment]
Good job!

**Comment by alexbeatnik** [comment]
Cool upgrade!

**Comment by Flower1111** [comment]
Good job

**Pull request merged**
